### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by davebneufeld** [maxi07/Teams-Presence-Govee#1]
Hi, I dont have an issue with your software but unfortunately there is no way to contact you within Github that I can see. 
I was thinking about building the same thing yesterday and found your repo here on github. 
I would like to try out your project but I need to purchase a Govee device and I wanted to ask you which bulb you used?
 
https://ca.govee.com/collections/smart-led-bulbs
is it this one?
https://ca.govee.com/collections/smart-led-bulbs/products/wi-fi-led-bulb

Thanks
you can email me at govee@daveneufeld.com
https://github.com/davebneufeld

or reply via this issue.

**Comment by maxi07** [comment]
Hey there, 
I coded the app using this LED strip from Amazon:
https://www.amazon.de/gp/product/B07Q79FC47/

Hope this helps!
